### PR TITLE
Instructions for using with renv

### PR DESCRIPTION
**Pull request by martinmodrak**
`renv` is a package management solution for R that mostly works and is getting popular, so I thought I'll add a few notes on how to setup this repository with `renv`.

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Thanks @martinmodrak!

**Comment by jgabry** [comment]
Thanks!

**Comment by martinmodrak** [comment]
Is something blocking merging this? I know have to come back to this PR to remember my instructions, having them on the r-packages site would help :-D

**Comment by rok-cesnovar** [comment]
Nothing is preventing it, I just usually let the PR author merge it.

**Comment by martinmodrak** [comment]
Oh, I see. Thanks!

**Pull request merged**
